name: "Packages: update"

on:
  workflow_dispatch:
  schedule:
    - cron: "25 4 * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  update-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Update flake packages
        uses: selfuryon/nix-update-action@v1
